### ISSUE TITLE
Is the link broken?

### ISSUE THREAD

**Issue by greendoescode** [Zoiter7/DailyStatistics#2]

**Comment by greendoescode** [comment]
spigot page link btww

**Comment by kb079** [comment]
Hello

You can download it here: https://github.com/Zoiter7/DailyStatistics/releases
Or direct download is: https://github.com/Zoiter7/DailyStatistics/releases/download/1.2/DailyStatistics-1.2.jar

**Comment by Zoiter7** [comment]
Hello

You can download it here: https://github.com/Zoiter7/DailyStatistics/releases
Or direct download is: https://github.com/Zoiter7/DailyStatistics/releases/download/1.2/DailyStatistics-1.2.jar

**Comment by greendoescode** [comment]
Thxs! Its fine now  have it installed! Thanks :)
